### ISSUE TITLE
Imágenes frontales de credenciales que aprecen sin rostro

### ISSUE THREAD

**Issue by Ramaznaz** [mensa-mx/migration#11]
Miembros que sí tienen fotografía -y en algunos casos revisé ya está normalizada- aparece su credencial sin ninguna foto, solo el resaque en blanco.

**Comment by maturanomx** [comment]
Si ya identificaste algún(os) caso concreto menciónalo. Entre mayor información se proporcione será más simple y rápida la solución.

Ayúdame pues :wink: 

---

> **resaque.**
> 1. m. Cuba. Operación de recolectar los tubérculos que no se han cosechado en la primera recogida.
> 2. m. Ec. Persona notablemente parecida a otra. La chica es el resaque de su abuela.

**Comment by maturanomx** [comment]
_Comment by @Ramaznaz_

---

Err... en realidad solo 4 de todas las credenciales tienen foto, de manera que creo que me tardaría mucho sacando foto por foto de cada una (se pierde el sentido de la automatización), así que te doy 3 ejemplos:
id jpeg
71224 06fad0ce73fdef2f104517ca295aaf78
54593 ff17ab0eb517b7629f40c56c5b86fbe1
71233 36673371c3e7af5306b425dc4d73fdac

**Comment by Ramaznaz** [comment]
No encontraba el otro.... este... el nuevo... pensé que habías cerrado el issue o.O

**Comment by maturanomx** [comment]
... error administrativo; no se compartió el resultado final.
