### ISSUE TITLE
Recuperar fotos de perfíl de los miembros

### ISSUE THREAD

**Issue by maturanomx** [mensa-mx/migration#4]
**Issue by [maturano](https://github.com/maturano)**
_Monday Dec 08, 2014 at 22:39 GMT_

---
- [x] Recuperar imágenes del viejo sistema (95252692595f5f10b72e25b2e526eee14b1ca0eb)
- [x] Recuperar archivos de Gdrive (e7d0ecf37e14a9377af12de2c05aebd76a9df2e5)
- [x] Buscar posibles asociaciones (588ce89d6775cee671d95212b9671e2d8eb0361a) (28e6cb7bbc6d6a281ee7fe26927bbf62aff2a130)

**Comment by maturanomx** [comment]
**Comment by [Ramaznaz](https://github.com/Ramaznaz)**
_Tuesday Dec 23, 2014 at 23:54 GMT_

---

Sí, me refería a obtener imágenes de los miembros qeu aún no tienen y subirlas a Gdrive para luego tener el link de ahí.
Y si… me puedes dar una lista de los que haya falta solicitarles fotografía para escribirles :)

**Comment by maturanomx** [comment]
@Ramaznaz 
Salvo una docena de archivos, ya se recuperan las fotografías de todo lo que se pudo. Envío al correo de membresías una lista de miembros (sin importar el estatus de su membresía) que no tienen fotografía. Si necesitas algún otro dato y/o filtrado házmelo saber.

Se trabaja ahora en la normalización de esas fotos... :/

**Comment by Ramaznaz** [comment]
Yeah!

**Comment by maturanomx** [comment]
263 archivos recuperados como perfil de diversas fuentes.
